[package]
name = "cops"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
spinlock = { git = "https://github.com/Starry-OS/spinlock.git" }
# spin = { version = "0.9", features = ["use_ticket_mutex"] }
buddy_system_allocator = "0.6"